### ISSUE TITLE
sonarr_tag_nohl.py - TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by bakerboy448** [s0up4200/scripts-for-the-arrs-and-brrs#9]
2023-07-19 17:34:21,730 INFO: Getting list of tags from Sonarr
2023-07-19 17:34:21,735 INFO: Tag hardlinked does not exist, creating it.
Traceback (most recent call last):
  File "/opt/soup-scripts/sonarr_tag_nohl.py", line 184, in <module>
    check_tag(tag_map)
  File "/opt/soup-scripts/sonarr_tag_nohl.py", line 85, in check_tag
    tag_map[new_tag['label']] = new_tag['id']
TypeError: list indices must be integers or slices, not str

bakerboy448@hetz-baker-2004:/opt/soup-scripts$ python3 --version
Python 3.10.12

**Comment by bakerboy448** [comment]
errr most likely ID-10T baseurl config missing baseurl issue.
